### ISSUE TITLE
crashing when using the wireless tool on receiver or transmitter block 

### ISSUE THREAD

**Issue by idkwhatimdoinggg** [Razzokk/Wireless-Redstone#7]
[crash-2024-03-10_19.41.41-server.txt](https://github.com/Razzokk/wireless-redstone/files/14552367/crash-2024-03-10_19.41.41-server.txt)

**Comment by idkwhatimdoinggg** [comment]
https://mclo.gs/HHvzS5C sorry about the download heres the mc log

**Comment by idkwhatimdoinggg** [comment]
using 1.20.2 on 1.20.4

**Comment by Razzokk** [comment]
Thanks for reporting! Should be solved for the port to MC 1.20.4. I'll leave this open until you can confirm it works and than will close this issue.

Btw. thanks for giving me the log and showing me [https://mclo.gs](https://mclo.gs/HHvzS5C). Didn't know this exists, it's amazing.
