### ISSUE TITLE
Can not load properly

### ISSUE THREAD

**Issue by LuckyDog322** [Razzokk/Wireless-Redstone#9]
1.20.1
version：1.1.2
[crash-2024-06-25_12.01.20-fml.txt](https://github.com/user-attachments/files/15964575/crash-2024-06-25_12.01.20-fml.txt)

**Comment by Razzokk** [comment]
Thanks for the report! Will investigate in the upcoming week.

**Comment by Razzokk** [comment]
Note that this is a race condition which means that it doesn't neccessarily happen all the time, it could be that you have been unaffected this far.

The following versions of the mod are also affected by this *potential* issue:

- 1.18.2 - Forge
- 1.19.2 - Forge
- 1.19.4 - Forge
- 1.20.1 - Forge
- 1.20.4 - Forge, NeoForge

A fix for all of them has been uploaded to the [CurseForge](https://www.curseforge.com/minecraft/mc-mods/wirelessredstone) and [Modrinth](https://modrinth.com/mod/wirelessredstone) page, simply grab the newest version of the mod for the respective minecraft version and you should not run into this problem.
